### ISSUE TITLE
Checklist for writing PolicyReport KEP

### ISSUE THREAD

**Issue by anusha94** [kubernetes-sigs/wg-policy-prototypes#112]
The Policy WG  presented to SIG-Auth on [7th Dec, 2022](https://docs.google.com/document/d/1woLGRoONE3EBVx-wTb4pvp4CI7tmLZ6lS26VTbosLKM/edit#heading=h.r4vs9ox1x3g0) and we have their approval and support to submit a KEP to promote the [Policy Report CRD](https://github.com/kubernetes-sigs/wg-policy-prototypes/tree/master/policy-report) to an official Kubernetes API! :tada:

We want to cleanup on the APIs and make any other changes that are needed before we write and submit the KEP. The below checklist (not final) is to track all such items. Feel free to update this list or comment if there are any concerns.

### Tasks
- [x] fix #96 
- [x] communicate to all stakeholders (see below) about the KEP proposal and get any feedback on the PolicyReport API
- [x] any changes to APIs will be now done for `v1beta1`
- [ ] follow k8s API best practices ([K8s API Conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md))
- [ ] raise PRs in repositories consuming PolicyReport CRD with any changes
- [ ] revisit project structure for apis
- [x] identify KEP prerequisites from [this doc](https://github.com/kubernetes/enhancements/blob/master/keps/README.md)

### Stakeholders

- [ ] Policy Reporter
- [ ] Kyverno
- [ ] Falco sidekick
- [ ] trivy-adapter
- [ ] Open Cluster Management
- [ ] RedHat ACM
- [ ] KubeArmor
- [ ] kube-bench adapter
- [ ] jsPolicy
- [ ] trivy-operator-polr-adapter (https://github.com/fjogeleit/trivy-operator-polr-adapter)
- [ ] vulnerability-operator (https://github.com/ckotzbauer/vulnerability-operator)
- [ ] tracee-polr-adapter (https://github.com/fjogeleit/tracee-polr-adapter)

**Comment by gparvin** [comment]
Additional stakeholder:
Open Cluster Management CNCF sandbox project https://open-cluster-management.io/ and Red Hat ACM product https://www.redhat.com/en/resources/advanced-cluster-management-kubernetes-datasheet

**Comment by sunstonesecure-robert** [comment]
can we change the issue title to mention PolicyReport so in Slack links people see what it refers to? thanks!

**Comment by fjogeleit** [comment]
Current state of api/client forks

* Policy Reporter uses its own fork/copy of the PolicyReport Go APIs and Clients
* jsPolicy uses its own fork/copy of the PolicyReport Go APIs and Clients
* trivy-operator-polr-adapter uses its own fork/copy of the PolicyReport Go APIs and Clients
* tracee-polr-adapter uses the Kyverno APIs and Client as dependency
* Falcosidekick uses the API and Client from `kube-bench-adapter` (outdated)
* kube-bench adapter uses the API and Client from `kubernetes-sigs/wg-policy-prototypes`
* KubeArmor adapter uses the API and Client from `kubernetes-sigs/wg-policy-prototypes`
* Trivy Adapter adapter uses the API and Client from `kubernetes-sigs/wg-policy-prototypes`
* vulnerability-operator uses the API and Client from `kubernetes-sigs/wg-policy-prototypes`
